// Components
import Head from "next/head";
import PostContent from "@/components/PostContent/PostContent";
import { GetStaticPropsContext, NextPage } from "next";
import { Post } from "@/interfaces";
import { useServiceQuery } from "@/Utilities/Services";
import { convertDatePost } from "@/Utilities/Convert";

// Utilities
// Interfaces

interface PageSlugProps {
  post: Post;
}

const PageSlug: NextPage<PageSlugProps> = ({ post }) => {
  const updatedDate = convertDatePost(post.updatedAt);

  return (
    <>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full min-h-screen py-0 ">
        <PostContent post={post} />
      </main>
    </>
  );
};

export default PageSlug;

export function getStaticPaths() {
  return {
    paths: [],
    fallback: "blocking",
  };
}

export async function getStaticProps({ params }: GetStaticPropsContext) {
  const { getPostBySlug } = await useServiceQuery();
  const { slug } = params as { slug: string };

  const postResponse = await getPostBySlug(slug);

  if (!postResponse) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      post: postResponse,
    },
    revalidate: 60 * 60 * 1, // 1 hour
  };
}
