// Components
import Head from "next/head";
import Image from "next/image";


// Utilities
// Interfaces

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full min-h-screen py-0">
        <section className=" text-center lg:text-start items-center bg-blog bg-cover pt-28 lg:pt-0 lg:mt-28">
          <div className="container grid grid-cols-1 lg:grid-cols-2 lg:gap-x-11">
            <div className="py-7 lg:py-16 flex flex-col">
              <div className=" flex flex-col lg:flex-row items-center lg:items-end gap-5">
                <h1 className="mt-4 text-3xl font-medium  lg:text-5xl text-green-500 flex gap-4 order-2 lg:order-1">
                  Blog Imigrei
                </h1>
                <Image
                  src="/Home/bandeiras.png"
                  alt="Bandeiras de portugal e italia"
                  width={75}
                  height={35}
                  className="mx-auto lg:ml-0 order-1 lg:order-2"
                />
              </div>
              <p className="mx-auto mt-4 lg:mt-6 text-green-300 text-sm lg:text-xl max-w-md lg:ml-0">
                Dicas e conteúdo de qualidade criado por quem te deseja a melhor
                experiência de imigração para a Itália e Portugal!
              </p>
            </div>
            <Image
              src="/Blog/banner.png"
              alt="Imagem banner principal"
              width={352}
              height={283}
              className="self-end mx-auto"
            />
          </div>
        </section>
      </main>
    </>
  );
}
