// Components
import Head from "next/head";

// Utilities
// Interfaces

export default function Blog() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="bg-green-400 h-80 "></div>
      </main>
    </>
  );
}
