import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function CidadaniaPortuguesa() {
  return (
    <>
      <Head>
        <title>Cidadania Portuguesa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full min-h-screen py-0">
        <section className=" text-center lg:text-start items-center bg-cidadaniaPort bg-cover pt-16 lg:pt-0 lg:mt-28">
          <div className="container grid grid-cols-1 lg:grid-cols-5 lg:gap-x-11">
            <div className="py-7 lg:py-16 flex flex-col lg:col-span-3">
              <div className=" flex flex-col lg:flex-row items-center lg:items-end gap-5">
                <h1 className="mt-4 text-3xl font-medium  lg:text-5xl text-red-500 flex gap-4 order-2 lg:order-1">
                  Cidadania Portuguesa
                </h1>
                <Image
                  src="/bandeira-portugal.png"
                  alt="Bandeira de portugal"
                  width={36}
                  height={35}
                  className="mx-auto lg:ml-0 order-1 lg:order-2"
                  priority
                />
              </div>
              <p className="mx-auto mt-4 lg:mt-6 text-red-400 text-sm lg:text-xl max-w-md lg:ml-0  lg:leading-6">
                Conheça o nosso serviço de consultoria voltado para você que
                quer conquistar a tão sonhada cidadania portuguesa!
              </p>
            </div>
            <Image
              src="/Servicos/Banner-cidadania-portuguesa.png"
              alt="Imagem banner principal"
              width={399}
              height={290}
              className="self-end mx-auto mt-5 lg:col-span-2"
              priority
            />
          </div>
        </section>
        <section className="lg:container">
          <div className="text-center lg:text-start container grid grid-cols-1 lg:grid-cols-2 items-center gap-16 mt-12 lg:my-20 box-white">
            <Image
              src="/Servicos/Section-one-sp.png"
              alt="imagem de um homem e uma mulher sorrindo"
              width={495}
              height={370}
              className="order-2 lg:order-1 mx-auto"
              priority
            />

            <div className="order-1 lg:order-2 flex flex-col">
              <span className="mt-4 text-green-500 font-medium">
                Sobre o serviço
              </span>
              <h2 className="mt-2 text-2xl sm:text-4xl text-black-400 font-medium">
                Cidadania portuguesa para descendentes
              </h2>
              <p className="text-sm sm:text-base mt-4 text-gray-300 lg:leading-5">
                A solicitação da cidadania portuguesa é um processo regido ente
                o consulado do brasil e portugual que dura, em média, 3 anos
                para a sua conclusão. Os bisnetos, netos e filhos de portugueses
                poderão solicitar a cidadania!
              </p>
            </div>
          </div>
        </section>
        <section className="container mt-14 lg:mt-32 mb-12 lg:mb-32 flex  px-24 lg:px-0 flex-col lg:flex-row  justify-center  gap-y-9 lg:gap-x-20">
          <div className="icons-service">
            <Image
              src="/Servicos/figure1.svg"
              alt="figure 1"
              width={50}
              height={50}
              className="w-9 h-9 lg:h-auto lg:w-auto"
            />
            <p>Processo descomplicado</p>
          </div>
          <div className="icons-service">
            <Image
              src="/Servicos/figure2.svg"
              alt="figure 2"
              width={50}
              height={50}
              className="w-9 h-9 lg:h-auto lg:w-auto"
            />
            <p>Segurança, rapidez e tecnologia</p>
          </div>
          <div className="icons-service">
            <Image
              src="/Servicos/figure3.svg"
              alt="figure 3"
              width={50}
              height={50}
              className="w-9 h-9 lg:h-auto lg:w-auto"
            />
            <p>Advogados especializados</p>
          </div>
          <div className="icons-service">
            <Image
              src="/Servicos/figure4.svg"
              alt="figure 4"
              width={50}
              height={50}
              className="w-9 h-9 lg:h-auto lg:w-auto"
            />
            <p>Pagamento facilitado</p>
          </div>
          <div className="icons-service">
            <Image
              src="/Servicos/figure5.svg"
              alt="figure 5"
              width={50}
              height={50}
              className="w-9 h-9 lg:h-auto lg:w-auto"
            />
            <p>Suporte personalizado</p>
          </div>
        </section>
        <section className="py-10">
          <div className="bg-green-400 pt-16">
            <div className="text-center container">
              <span className="text-green-500 font-medium">Como Funciona</span>
              <h2 className="mt-2  text-2xl sm:text-4xl text-black-400 font-medium">
                Entenda o nosso processo em 3 etapas
              </h2>
              <p className="text-base mt-4 text-gray-300 mx-auto max-w-2xl px-2   lg:leading-5 ">
                A nossa consultoria é dividida, basicamente, em três etapas que
                garantem organização e eficácia no processo de conquista da
                cidadania portuguesa.
              </p>
            </div>
          </div>
          <div className="pt-10 box-servicos">
            <div className="container flex flex-col items-center gap-y-4 lg:flex-row justify-center gap-x-6 ">
              <div className=" bg-white-500 w-[360px] h-auto shadow-2xl  py-5 lg:py-9  px-5 lg:px-7 flex gap-x-6 flex-row lg:flex-col justify-start items-start">
                <div className="bg-yellow-500 border px-6 lg:px-2  font-bold rounded-[100%] w-[47px] h-[47px] lg:w-[73px] lg:h-[73px] text-4xl lg:text-5xl text-red-500 flex justify-center items-center">
                  <span>1</span>
                </div>
                <div className="">
                  <h3 className=" text-base lg:text-xl font-medium text-black-400 lg:mt-10">
                    Organização
                  </h3>
                  <p className=" text-sm lg:text-base text-gray-300 mt-3">
                    Oferecemos uma variedade de serviços para os nossos
                    assessorados que buscam o sonho de viver em Portugal e
                    Itália!
                  </p>
                </div>
              </div>

              <div className=" bg-white-500 w-[360px] h-auto shadow-2xl  py-5 lg:py-9  px-5 lg:px-7 flex gap-x-6 flex-row lg:flex-col justify-start items-start">
                <div className="bg-yellow-500 border px-6 lg:px-2  font-bold rounded-[100%] w-[47px] h-[47px] lg:w-[73px] lg:h-[73px] text-4xl lg:text-5xl text-red-500 flex justify-center items-center">
                  <span>2</span>
                </div>
                <div className="">
                  <h3 className=" text-base lg:text-xl font-medium text-black-400 lg:mt-10">
                    Pedido de Cidadania
                  </h3>
                  <p className=" text-sm lg:text-base text-gray-300 mt-3">
                    Oferecemos uma variedade de serviços para os nossos
                    assessorados que buscam o sonho de viver em Portugal e
                    Itália!
                  </p>
                </div>
              </div>

              <div className=" bg-white-500 w-[360px] h-auto shadow-2xl  py-5 lg:py-9  px-5 lg:px-7 flex gap-x-6 flex-row lg:flex-col justify-start items-start">
                <div className="bg-yellow-500 border px-6 lg:px-2  font-bold rounded-[100%] w-[47px] h-[47px] lg:w-[73px] lg:h-[73px] text-4xl lg:text-5xl text-red-500 flex justify-center items-center">
                  <span>3</span>
                </div>
                <div className="">
                  <h3 className=" text-base lg:text-xl font-medium text-black-400 lg:mt-10">
                    Entrega de Materiais
                  </h3>
                  <p className=" text-sm lg:text-base text-gray-300 mt-3">
                    Oferecemos uma variedade de serviços para os nossos
                    assessorados que buscam o sonho de viver em Portugal e
                    Itália!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
