// Components
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// Utilities
// Interfaces

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen py-0">
        <section className=" text-center lg:text-start items-center bg-green-400 pt-28">
          <div className="container grid grid-cols-1 lg:grid-cols-2 lg:gap-x-11">
            <div className="py-4 lg:py-16 flex flex-col">
              <Image
                src="/Home/bandeiras.png"
                alt="Bandeiras de portugal e italia"
                width={75}
                height={35}
                className="mx-auto lg:ml-0"
              />
              <h1 className="mt-4 text-3xl font-medium  lg:text-5xl text-black-500">
                Assessoria de imigração para Portugal e Itália
              </h1>
              <p className="mx-auto mt-4 lg:mt-3 text-gray-300 text-sm lg:text-xl max-w-md lg:ml-0">
                Conquiste sua cidadania sem se preocupar com burocracias.
                Economize tempo e dinheiro com com a Imigrei!
              </p>
              <Link
                href="#"
                className=" mt-4 lg:mt-11 linkButton text-base  max-w-[209px] mx-auto lg:ml-0"
              >
                Conhecer Serviços
              </Link>
            </div>
            <Image
              src="/Home/banner.svg"
              alt="Imagem banner principal"
              width={426}
              height={418}
              className="self-end mx-auto"
            />
          </div>
        </section>
        <section className="text-center lg:text-start container grid grid-cols-1 lg:grid-cols-2 items-center gap-24 mt-12 lg:my-16 box-white">
          <Image
            src="/Home/quemSomos.svg"
            alt="imagem de uma mulher sorrindo"
            width={345}
            height={362}
            className="order-2 lg:order-1 mx-auto"
          />

          <div className="order-1 lg:order-2 flex flex-col">
            <span className="text-xs mt-10 sm:text-base text-green-500 font-medium">
              Quem Somos
            </span>
            <h2 className="mt-2 text-2xl sm:text-4xl text-black-400 font-medium text-">
              Prazer, somos a Imigrei!
            </h2>
            <p className="text-sm sm:text-base mt-4 text-gray-300">
              Oferecemos uma variedade de serviços para os nossos assessorados
              que buscam o sonho de viver em Portugal e Itália! Oferecemos uma
              variedade de serviços para os nossos assessorados que buscam o
              sonho de viver em Portugal e Itália!
            </p>
            <Link
              href="#"
              className="text-sm sm:text-base linkButton self-center lg:self-start my-4"
            >
              Solicitar Atendimento
            </Link>
          </div>
        </section>
      </main>
    </>
  );
}
